spring:
  datasource:
    url: "jdbc:h2:mem:demo"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-plataform: org.hiberante.dialect.H2Dialect
  h2:
    console:
      enabled: true
